name: flutter_tech_task
description: GÃ¶rev projesi.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.2.2
  iconsax_flutter: ^1.0.0
  intl: ^0.19.0
  notification_permissions: ^0.6.1
  page_transition: ^2.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  timezone: ^0.9.1

dev_dependencies:
  build_runner: ^2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.0
  test: ^1.17.12

  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/l10n/
    - packages/timezone/data/latest_all.tzf
